### ISSUE TITLE
minikube node-hello

### ISSUE THREAD

**Issue by xxleyi** [xxleyi/learning_list#108]
在分别搞定 kubectl, minikube and docker hub image 之后，需要通过 kubectl 起一个 deployment 或者 pod，然后暴露服务到 minikube。

在此过程中，遇到的坑主要是怎么配置 kubectl 读取 docker 中的私有镜像。

官网提供了两种方式，第一种不需要密码明文的方式看着挺好，但用起来一直不起作用，也没找到原因所在。最终使用了第二种方式配置了一个 kube secrect，然后部署一个 pod 到相应 secrect 之下，而且为了暴露出服务，需要配置一个 label。

重要的是配置：

```
apiVersion: v1
kind: Pod
metadata:
  name: node-hello
  labels:
    app: node
spec:
  containers:
  - name: node-hello-container
    image: docker.io/xileyi/first-repo:latest
  imagePullSecrets:
  - name: regcred
```

`kubectl create secret docker-registry regcred --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> -n <your-namespace>`
