### ISSUE TITLE
CSS Inheritance

### ISSUE THREAD

**Issue by xxleyi** [xxleyi/learning_list#228]
Some CSS attributes inherit from parent, while some don't, it mostly lives up to our common sense.

For example, color and font-size inherit, width and height don't.

Look for specs if you can not be sure.

About inheritance, we can alter by
- unset
- inherit
- initial

In some cases, we want apply a css rule to all descendants of an element, which is also one form of inheritance, which is done by developer.

HOW?

```css
/* the star is the key */
.some-class * {
    overflow: hidden;
}
```

Similarly, we can also apply a css rule to all children of an element.

```css
/* > and * is the key */
.some-class > * {
    overflow: hidden;
}
